

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-img-srvr-deployment
  labels:
    app: api-img-srvr
spec:
  replicas: 0
  selector:
    matchLabels:
      app: api-img-srvr
  template:
    metadata:
      labels:
        app: api-img-srvr 
    spec:
      containers:
      - name: apiimgserver
        image: iliyasll/api-img-srvr:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
   name: api-img-srvr-service
spec:
   selector:
      app: api-img-srvr   
   type: LoadBalancer
   ports:
   - protocol: TCP
     port: 5000
     targetPort: 3000
     nodePort: 31110
